# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.doctrine_listener.image_update:
        class: OC\PlatformBundle\DoctrineListener\ImageUpdateListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    oc_platform.doctrine_listener.advert_update:
        class: OC\PlatformBundle\DoctrineListener\AdvertUpdateListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            
    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purger\AdvertPurger
        arguments:
            - "@doctrine.orm.entity_manager"

    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - 50
        calls:
            - [ setLocale, [%locale%] ]

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
            -  { name: twig.extension }

    oc_platform.form.ckeditor:
        class: OC\PlatformBundle\Form\CkeditorType
        tags:
          - { name: form.type, alias: ckeditor }

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platform.beta.html_adder"
            - "2016-10-16"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    oc_platform.bigbrother.message_notificator:
        class: OC\PlatformBundle\Bigbrother\MessageNotificator
        arguments:
            - "@mailer"

    oc_platform.bigbrother.message_listener:
        class: OC\PlatformBundle\Bigbrother\MessageListener
        arguments:
            - "@oc_platform.bigbrother.message_notificator"
            - ["alexandre", "marine", "pierre", "Henry Truc"]
        tags:
             - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage }