<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class AdvertRepository extends EntityRepository
{

	// comme findAll mais ne retourne pas un résultat, mais une requète
	public function getAdverts()
	{

		return $this->createQueryBuilder('a')
		    ->orderBy('a.date', 'DESC')
	    	->getQuery()
		;
	}

	public function getAdvert($id)
	{

		return $this->createQueryBuilder('a')
	    ->where('a.id = :id')
	    ->setParameter('id', $id)
	    ->leftJoin('a.categories', 'c')
	    ->addSelect('c')
	    ->leftJoin('a.user', 'u')
	    ->addSelect('u')
	    ->leftJoin('a.applications', 'app')
	    ->addSelect('app')
	    ->leftJoin('a.skills', 's')
	    ->addSelect('s')
	    ->leftJoin('s.skill', 'skill')
	    ->addSelect('skill')
	    ->leftJoin('a.image', 'i')
	    ->addSelect('i')
    	->getQuery()
    	->getOneOrNullResult()
		;
	}

	public function getAdvertToPurge($date)
	{

		return $this->createQueryBuilder('a')
			->where('a.updatedAt < :last')
			->orWhere('a.updatedAt IS NULL AND a.date <= :last') // Si la date de modification est vide, on vérifie la date de création
			->andWhere('a.applications is empty')
			->setParameter('last', $date) // récupère toutes les annonces dont la date de modification est plus vieille que X jours
			->getQuery()
			->getResult()
		;
	}

}
