<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

	public function getApplicationsWithAdvert($limit)
	{

		return $this->createQueryBuilder('a')
			->leftJoin('a.advert', 'adv')
		  	->addSelect('adv')
			->setMaxResults($limit)
			->orderBy('a.date', 'DESC')
			->getQuery()
			->getResult()
		;
	}

}
